name: php                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  sast_phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
       docker pull phpstan/phpstan
       docker run -v $(pwd):/src --rm phpstan/phpstan analyse --error-format=json /src > phpstan-output-docker.json
